In [225]:
import pandas as pd

# Read the Excel file
file_path = '../excel/out/US/Credit/HY/t_0/reccursive/sectors_regs_summary.xlsx'
data = pd.read_excel(file_path)

leg = pd.read_excel("../excel/in/legendas.xlsx")
# Display the first few rows of the dataframe
display(data.head())

,Unnamed: 0,idx,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q (coef),NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,f(pval),NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp (coef),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
3,3,g(pval),(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
4,4,jpm_vol (coef),NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886

In [226]:
data.rename(columns={"idx": "Codes"}, inplace=True)
data.insert(data.columns.get_loc("Codes") + 1, "Names", "")
display(data)

,Unnamed: 0,Codes,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q (coef),,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,f(pval),,NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp (coef),,-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
3,3,g(pval),,(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
4,4,jpm_vol (coef),,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
5,5,j(pval),,NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
6,6,move (coef),,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
7,7,m(pval),,NaN,NaN,NaN,NaN,NaN,NaN,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
8,8,ted_spread_us (coef),,1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
9,9,t(pval),,(0.0),(0.0),(0.0),(0.0),(0.058),NaN,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
10,10,vix (coef),,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
11,11,v(pval),,NaN,NaN,NaN,NaN,(0.0),(0.0),(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
12,12,intercept (coef),,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
13,13,i(pval),,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,14,AIC,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [227]:
data.insert(data.columns.get_loc("Codes") + 1, "coef", data['Codes'].str.endswith('(coef)'))
data.insert(data.columns.get_loc("Codes") + 2, "pval", data['Codes'].str.endswith('(pval)'))

In [228]:
for idx, i in data['coef'].items():
    if i == True:
        data.at[idx, 'Codes'] = data.at[idx, 'Codes'].replace(" (coef)", "")
        

for idx, i in data['pval'].items():
    if i == True:
        data.at[idx, 'Codes'] = data.at[idx - 1, 'Codes']

In [229]:
mapping = dict(zip(leg["Codes"], leg["Names"]))
print(mapping)

for idx, code in data["Codes"].items():
    if code in mapping:
        data.at[idx, "Names"] = mapping[code]

{'ted_spread_us': 'Ted Spread US (%)', 'ted_spread_eur': 'Ted Spread Europe (%)', 'fed_funds': 'Fed Funds (%)', '3m_nom_us': '3m Bill US (%)', '3m3m_nom_us': '3m3m Forward', '6m_nom_us': '6m Bill US (%)', '1y_nom_us': '1y Bill US (%)', '2y_nom_us': '2y Note US (%)', '5y_nom_us': '5y Note US (%)', '10y_nom_us': '10y Note US (%)', '10y_real_us': '10y TIPS (%)', '5y5y_be_us': '5Y5Y TIPS BE (%)', '3m_nom_ger': '3m Bill Germany (%)', '2y_nom_ger': '2y Note Germany (%)', '2y_nom_fra': '2y Note France (%)', '2y_nom_net': '2y Note Netherlands (%)', '2y_nom_ita': '2y Note Italy (%)', '2y_nom_spa': '2y Note Spain (%)', '2y_nom_por': '2y Note Portugal (%)', '5y_nom_ger': '5y Note Germany (%)', '5y_nom_fra': '5y Note France (%)', '5y_nom_net': '5y Note Netherlands (%)', '5y_nom_ita': '5y Note Italy (%)', '5y_nom_spa': '5y Note Spain (%)', '5y_nom_por': '5y Note Portugal (%)', '10y_nom_ger': '10y Note Germany (%)', '10y_nom_fra': '10y Note France (%)', '10y_nom_net': '10y Note Netherlands (%)', '10y_nom_ita': '10y Note Italy (%)', '10y_nom_spa': '10y Note Spain (%)', '10y_nom_por': '10y Note Portugal (%)', '2y_nom_eur_weig_all': '2y Nom Europe All weighted Agg (%)', '5y_nom_eur_weig_all': '5y Nom Europe All weighted Agg (%)', '10y_nom_eur_weig_all': '10y Nom Europe All weighted Agg (%)', '2y_nom_spread_weig_eur_ger_all': '2y Nom Europe Spread All Weighted Agg (%)', '5y_nom_spread_weig_eur_ger_all': '5y Nom Europe Spread All Weighted Agg (%)', '10y_nom_spread_weig_eur_ger_all': '10y Nom Europe Spread All Weighted Agg (%)', '2y_nom_spread_eur_ger': '2y Nom Europe Simple Spread All Agg (%)', '5y_nom_spread_eur_ger': '5y Nom Europe Simple Spread All Agg (%)', '10y_nom_spread_eur_ger': '10y Nom Europe Simple Spread All Agg (%)', '2y_nom_jp': '3y JGB (%)', '5y_nom_jp': '5y JGB (%)', '10y_nom_jp': '10y JGB (%)', '2y_nom_spread_ger_us': '2y Nom Spread GE-US (%)', '5y_nom_spread_ger_us': '5y Nom Spread GE-US (%)', '10y_nom_spread_ger_us': '10y Nom Spread GE-US (%)', 'incl_2y10y_us': '10y-2y Spread US (%)', 'incl_2y10y_ger': '10y-2y Spread Germany (%)', 'usdjpy_1y_hedge_cost': 'JPY Hedge Cost 1y (% aa)', 'usdjpy_3m_hedge_cost': 'JPY Hedge Cost 3m (% aa)', 'usdeur_1y_hedge_cost': 'EUR Hedge Cost 1y (% aa)', 'usdeur_3m_hedge_cost': 'EUR Hedge Cost 3m (% aa)', 'avg_1y_hedge_cost': 'Average Hedge Cost 1y (% aa)', 'avg_3m_hedge_cost': 'Average Hedge Cost 3m (% aa)', 'jpy5y_dif_1y_cost': 'JPY 5y diff (-) Hedge cost 1y', 'jpy5y_dif_3m_cost': 'JPY 5y diff (-) Hedge cost 3m', 'eur5y_dif_1y_cost': 'EUR 5y diff (-) Hedge cost 1y', 'eur5y_dif_3m_cost': 'EUR 5y diff (-) Hedge cost 3m', 'avg5y_dif_1y_cost': 'AVG 5y diff (-) Hedge cost 1y', 'avg5y_dif_3m_cost': 'AVG 5y diff (-) Hedge cost 3m', 'jpy10y_dif_1y_cost': 'JPY 10y diff (-) Hedge cost 1y', 'jpy10y_dif_3m_cost': 'JPY 10y diff (-) Hedge cost 3m', 'eur10y_dif_1y_cost': 'EUR 10y diff (-) Hedge cost 1y', 'eur10y_dif_3m_cost': 'EUR 10y diff (-) Hedge cost 3m', 'avg10y_dif_1y_cost': 'AVG 10y diff (-) Hedge cost 1y', 'avg10y_dif_3m_cost': 'AVG 10y diff (-) Hedge cost 3m', '10y_real_ger': '10y Real Note Germany (%)', 'usdjpy': 'USDJPY', 'eurusd': 'EURUSD', 'CDX_US_IG_spread': 'CDX IG US Index', 'CDX_US_HY_spread': 'CDX HY US Index', 'CDX_EZ_IG_spread': 'CDX IG BBG', 'CDX_EZ_HY_spread': 'CDX HY BBG', 'vix': 'VIX SPX', 'v2x': 'VIX Eurostoxx', 'jpm_vol': 'JPM FX Vol', 'move': 'MOVE', 'wti': 'WTI', 'liq_ratio': 'Ratio: (Fed Excess reserves + Reverse Repos) to (Treasuries and Notes outside the Fed)', 'liq_ratio_wo_repo': 'Ratio: (Fed Excess reserves) to (Treasuries and Notes outside the Fed)', 'fed_share_ust_wo_bills': 'Fed Share of UST Market w/o Bills (%)', 'fed_share_ust': 'Fed Share of UST Market (%)', 'ecb_qe_rt': 'Ratio to GDP: ECB Securities of Euro Residents Denominated in Euro Balance', 'ecb_corp_qe_rt': 'Ratio to GDP: ECB Corp Sector Purchase Balance', 'ecb_corp_qe_purch_rt': 'Ratio to GDP: ECB Corp Sector Purchase Programme Weekly Purchases', 'ecb_corp_qe_redemp_rt': 'Ratio to GDP: ECB Corp Sector Purchase Programme Weekly Redemptions', 'ez_pmi_comp_ZS': 'Eurozone Composite PMI SA (ZS)', 'ez_pmi_manuf_ZS': 'Eurozone Manufacturing PMI SA (ZS)', 'ez_pmi_serv_ZS': 'Eurozone Services PMI SA (ZS)', 'ism_manuf_ZS': 'ISM Manufacturing (ZS)', 'ism_serv_ZS': 'ISM Service (ZS)', 'global_pmi_comp': 'Global PMI Composite (ZS)', 'global_pmi_comp_ZS': 'Global PMI Composite (ZS)', 'global_pmi_manuf_ZS': 'Global PMI Manufacturing (ZS)', 'global_pmi_serv_ZS': 'Global PMI Service (ZS)', 'payroll_us_1m': 'Payroll (1m %chg)', 'ip_manuf_us_1m': 'US Industrial Production SA (1m %chg)', 'ret_sal_us_1m': 'US Retail Sales SA (1m %chg)', 'ip_manuf_ez_1m': 'Eurostat Industrial Production Eurozone SWDA (1m %chg)', 'ret_sal_ez_1m': 'Eurostat Retail Sales Volume Eurozone SWDA (1m %chg)', 'payroll_us_3m': 'Payroll (3m %chg)', 'ip_manuf_us_3m': 'US Industrial Production SA (3m %ave chg)', 'ret_sal_us_3m': 'US Retail Sales SA (3m %ave chg)', 'ip_manuf_ez_3m': 'Eurostat Industrial Production Eurozone SWDA (3m %ave chg)', 'ret_sal_ez_3m': 'Eurostat Retail Sales Volume Eurozone SWDA (3m %ave chg)', 'payroll_us_6m': 'Payroll (6m %ave chg)', 'ip_manuf_us_6m': 'US Industrial Production SA (6m %ave chg)', 'ret_sal_us_6m': 'US Retail Sales SA (6m %ave chg)', 'ip_manuf_ez_6m': 'Eurostat Industrial Production Eurozone SWDA (6m %ave chg)', 'ret_sal_ez_6m': 'Eurostat Retail Sales Volume Eurozone SWDA (6m %ave chg)', 'payroll_us_12m': 'Payroll (12m %ave chg)', 'ip_manuf_us_12m': 'US Industrial Production SA (12m %ave chg)', 'ret_sal_us_12m': 'US Retail Sales SA (12m %ave chg)', 'ip_manuf_ez_12m': 'Eurostat Industrial Production Eurozone SWDA (12m %ave chg)', 'ret_sal_ez_12m': 'Eurostat Retail Sales Volume Eurozone SWDA (12m %ave chg)', 'payroll_us_vol_2y': 'Payroll (3m %ave chg, 2y vol)', 'ip_manuf_us_vol_2y': 'US Industrial Production SA (3m %ave chg, 2y vol)', 'ret_sal_us_vol_2y': 'US Retail Sales SA (3m %ave chg, 2y vol)', 'ip_manuf_ez_vol_2y': 'Eurostat Industrial Production Eurozone SWDA (3m %ave chg, 2y vol)', 'ret_sal_ez_vol_2y': 'Eurostat Retail Sales Volume Eurozone SWDA (3m %ave chg, 2y vol)', 'payroll_us_vol_5y': 'Payroll (3m %ave chg, 5y vol)', 'ip_manuf_us_vol_5y': 'US Industrial Production SA (3m %ave chg, 5y vol)', 'ret_sal_us_vol_5y': 'US Retail Sales SA (3m %ave chg, 5y vol)', 'ip_manuf_ez_vol_5y': 'Eurostat Industrial Production Eurozone SWDA (3m %ave chg, 5y vol)', 'ret_sal_ez_vol_5y': 'Eurostat Retail Sales Volume Eurozone SWDA (3m %ave chg, 5y vol)', 'cpi_us_trail_2y': 'US CPI Urban Consumers (YoY, 2y average)', 'cpi_core_us_trail_2y': 'US CPI Urban Consumers Less Food & Energy (YoY, 2y average)', 'pce_core_us_trail_2y': 'US Core PCE Core Price Index (YoY, 2y average)', 'hcpi_ez_trail_2y': 'Euro Area CPI (YoY, 2y average)', 'hcpi_core_ez_trail_2y': 'Euro Area Core CPI (YoY, 2y average)', 'cpi_us_trail_5y': 'US CPI Urban Consumers (YoY, 5y average)', 'cpi_core_us_trail_5y': 'US CPI Urban Consumers Less Food & Energy (YoY, 5y average)', 'pce_core_us_trail_5y': 'US Core PCE Core Price Index (YoY, 5y average)', 'hcpi_ez_trail_5y': 'Euro Area CPI (YoY, 5y average)', 'hcpi_core_ez_trail_5y': 'Euro Area Core CPI (YoY, 5y average)', 'cpi_us_vol_2y': 'US CPI Urban Consumers (YoY, 2y vol)', 'cpi_core_us_vol_2y': 'US CPI Urban Consumers Less Food & Energy (YoY, 2y vol)', 'pce_core_us_vol_2y': 'US Core PCE Core Price Index (YoY, 2y vol)', 'hcpi_ez_vol_2y': 'Euro Area CPI (YoY, 2y vol)', 'hcpi_core_ez_vol_2y': 'Euro Area Core CPI (YoY, 2y vol)', 'cpi_us_vol_5y': 'US CPI Urban Consumers (YoY, 5y vol)', 'cpi_core_us_vol_5y': 'US CPI Urban Consumers Less Food & Energy (YoY, 5y vol)', 'pce_core_us_vol_5y': 'US Core PCE Core Price Index (YoY, 5y vol)', 'hcpi_ez_vol_5y': 'Euro Area CPI (YoY, 5y vol)', 'hcpi_core_ez_vol_5y': 'Euro Area Core CPI (YoY, 5y vol)', 'us_revenue_m': 'US Treasury Revenue (Bi) (Montlhy)', 'us_expenditures_m': 'US Treasury Expenditure (Bi) (Montlhy)', 'us_interest_m': 'US Treasury Net Interest (Bi) (Montlhy)', 'us_treas_bill': 'US Debt Held by the Public Outstanding Bills (Mi)', 'us_treas_note': 'US Debt Held by the Public Outstanding Notes (Mi)', 'us_treas_bond': 'US Debt Held by the Public Outstanding Bonds (Mi)', 'jpm_fri_gdp_us_ZS': 'JPMorgan GDP Forecast Revision Index US (ZS)', 'jpm_fri_cpi_us_ZS': 'JPMorgan CPI Forecast Revision Index US (ZS)', 'bbg_cdx_us_hy_tot_out': 'BBG HY Index Outstanding - Total', 'bbg_cdx_us_hy_BA_out': 'BBG HY Index Outstanding - BA Rating', 'bbg_cdx_us_hy_B_out': 'BBG HY Index Outstanding - B Rating', 'bbg_cdx_us_hy_CAA_out': 'BBG HY Index Outstanding - CAA Rating', 'bbg_cdx_us_hy_CAA_minus': 'BBG HY Index Outstanding - Below CAA Rating', 'credit_hh_ez': 'ECB Euro Area MFI Loans to Households Outstanding', 'credit_nonfin_corp_ez': 'ECB Euro Area MFI Loans to Non-Financial Corp Outstanding', 'output_gap_us_q': 'CBO US Real Output Gap (% GDP)', 'unemp_nat_us_q': 'CBO Natural Rate of Unemp. (%)', 'gdp_nom_us_q': 'GDP US Nominal (Bi) Dollars SAAR', 'gdp_cte_us_q': 'GDP US Chained 2012 (Bi) Dollars SAAR', 'gdp_qoq_us_q': 'GDP US Chained 2012 Dollars QoQ SA (%)', 'gdp_yoy_us_q': 'GDP US Chained 2012 Dollars YoY SA (%)', 'unemp_us_q': 'US Unemployment Rate (%)', 'spf_fed_gdp_y0_q': 'Fed SPF GDP Price Index SA Curr Year (Bi)', 'spf_fed_gdp_y1_q': 'Fed SPF GDP Price Index SA Curr Year +1 (Bi)', 'spf_fed_gdp_y2_q': 'Fed SPF GDP Price Index SA Curr Year +2 (Bi)', 'spf_fed_gdp_y3_q': 'Fed SPF GDP Price Index SA Curr Year +3 (Bi)', 'spf_fed_gdp_10y_q': 'Fed SPF 10Y GDP Growth', 'spf_fed_cpi_thisy_q': 'Fed SPF CPI SAAR Curr Year', 'spf_fed_cpi_nexty_q': 'Fed SPF CPI SAAR Curr Year +1', 'spf_fed_cpi_5y_q': 'Fed SPF 5Y CPI Inflation Rate', 'spf_fed_cpi_10y_q': 'Fed SPF 10Y CPI Inflation Rate', 'fed_sloos_ci_large_firms_tight_ZS': 'Fed Sloos Tight Std for C&I Loans (L&M-Market Firms) (ZS) (Smoothed)', 'fed_sloos_ci_small_firms_tight_q': 'Fed Sloos Tight Std for C&I Loans (Small Firms) (ZS) (Smoothed)', 'fed_sloos_ci_small_firms_tight_ZS': 'Fed Sloos Tight Std for C&I Loans (Small Firms) (ZS) (Smoothed)', 'ecb_sloos_cdt_std_3bck_ZS': 'ECB SLOOS Ave Net Lending All change 3m backward (ZS) (Smoothed)', 'ecb_sloos_cdt_std_3frw_ZS': 'ECB SLOOS Ave Net Lending All expected change 3m forward (ZS) (Smoothed)', 'ecb_sloos_cdt_dem_3bck_ZS': 'ECB SLOOS Ave Net Lending All change in demand 3m backward (ZS) (Smoothed)', 'ecb_sloos_cdt_dem_3frw_ZS': 'ECB SLOOS Ave Net Lending All expected change in demand 3m forward (ZS) (Smoothed)', 'corp_fin_gap_3M_gdp_q': 'Corporate Financing Gap (% GDP) (Smoothed)', 'corp_fin_gap_12M_gdp_q': 'Corporate Financing Gap (12M) (% GDP) (Smoothed)', 'corp_fin_gap_3M_jpm_gdp_q': 'Corporate Financing Gap JPM (% GDP) (Smoothed)', 'corp_fin_gap_12M_jpm_gdp': 'Corporate Financing Gap JPM (12M) (% GDP) (Smoothed)', 'hh_debt_gdp_us_q': 'Household Debt US (% GDP)', 'hh_debt_disp_inc_us_q': 'Household Debt US (% Disposable Income)', 'priv_debt_gdp_us_q': 'Private Debt US (% GDP)', 'corp_debt_gdp_us_q': 'Corporate Debt US (% GDP)', 'public_debt_gdp_us_q': 'Public Debt US (% GDP)', 'public_inmkt_debt_gdp_us_q': 'Public Debt in the Market US (% GDP)', 'gdp_nom_ez_q': 'GDP EMU Nominal (Mi) Euros SAAR', 'gdp_cte_ez_q': 'GDP EMU Chained 2012 (Mi) Euros SAAR', 'gdp_qoq_ez_q': 'GDP EMU Chained 2012 Dollars QoQ SA (%)', 'gdp_yoy_ez_q': 'GDP EMU Chained 2012 Dollars YoY SA (%)', 'output_gap_ez_q': 'BBG Euro Area Output Gap (%)', 'disp_inc_ez_q': 'EZ Gross Disposable Income (Bi)', 'gdp_nom_ger_q': 'Germany Nominal GDP (Bi)', 'gdp_nom_fra_q': 'France Nominal GDP (Bi)', 'gdp_nom_net_q': 'Netherlands Nominal GDP (Bi)', 'gdp_nom_ita_q': 'Italy Nominal GDP (Bi)', 'gdp_nom_spa_q': 'Spain Nominal GDP (Bi)', 'gdp_nom_por_q': 'Portugal Nominal GDP (Bi)', 'gdp_nom_ire_q': 'Ireland Nominal GDP (Bi)', 'debt_gdp_nom_ez_q': 'Eurozone Debt to GDP (%)', 'debt_gdp_nom_ger_q': 'Germany Debt to GDP (%)', 'debt_gdp_nom_fra_q': 'France Debt to GDP (%)', 'debt_gdp_nom_net_q': 'Netherlands Debt to GDP (%)', 'debt_gdp_nom_ita_q': 'Italy Debt to GDP (%)', 'debt_gdp_nom_spa_q': 'Spain Debt to GDP (%)', 'debt_gdp_nom_por_q': 'Portugal Debt to GDP (%)', 'debt_gdp_nom_ire_q': 'Ireland Debt to GDP (%)', 'spf_ecb_cpi_5y_q': 'ECB SPF HCPI 5 Years Ahead', 'spf_ecb_gdp_5y_q': 'ECB SPF GDP Growth 5 Years Ahead', 'bis_gli_int_claims_all_sec_gdp': 'BIS GLI International Claims on all Sectors (% GDP)', 'bis_gli_int_claims_bank_sec_gdp': 'BIS GLI International Claims on the Bank Sector (% GDP)', 'bis_gli_int_claims_non_bank_sec_gdp': 'BIS GLI International Claims on the Non-Bank Sectors (% GDP)', 'bis_gli_cross_border_claims_priv_non_fin_sec_gdp': 'BIS GLI Total Claims on Private Non-Financial Sector (% GDP)', 'bis_gli_total_claims_priv_non_fin_sec_gdp': 'BIS GLI Local Claims on Private Non-Financial Sector (% GDP)', 'bis_gli_local_claims_priv_non_fin_sec_gdp': 'BIS GLI Cross-Border Claims on Private Non-Financial Sector (% GDP)', 'bis_gli_us_claims_priv_non_fin_sec_gdp': 'BIS GLI Claims on US Private Non-Financial Sector (% GDP)', 'bis_gli_ez_claims_priv_non_fin_sec_gdp': 'BIS GLI Claims on EZ Private Non-Financial Sector (% GDP)', 'bis_gli_int_claims_all_sec_yoy': 'BIS GLI International Claims on all Sectors (YoY)', 'bis_gli_int_claims_bank_sec_yoy': 'BIS GLI International Claims on the Bank Sector (YoY)', 'bis_gli_int_claims_non_bank_sec_yoy': 'BIS GLI International Claims on the Non-Bank Sectors (YoY)', 'bis_gli_cross_border_claims_priv_non_fin_sec_yoy': 'BIS GLI Total Claims on Private Non-Financial Sector (YoY)', 'bis_gli_total_claims_priv_non_fin_sec_yoy': 'BIS GLI Local Claims on Private Non-Financial Sector (YoY)', 'bis_gli_local_claims_priv_non_fin_sec_yoy': 'BIS GLI Cross-Border Claims on Private Non-Financial Sector (YoY)', 'bis_gli_us_claims_priv_non_fin_sec_yoy': 'BIS GLI Claims on US Private Non-Financial Sector (YoY)', 'bis_gli_ez_claims_priv_non_fin_sec_yoy': 'BIS GLI Claims on EZ Private Non-Financial Sector (YoY)', 'fed_spf_payroll_disp_q': 'Fed SPF Payroll 1y (Dispersion P75 - P25) (%)', 'fed_spf_ip_disp_q': 'Fed SPF Industrial Production 1y (Dispersion P75 - P25) (%)', 'fed_spf_gdp1y_disp_q': 'Fed SPF GDP 1y (Dispersion P75 - P25) (%)', 'fed_spf_pce_disp_q': 'Fed SPF PCE 1y (Dispersion P75 - P25) (%)', 'fed_spf_nonresinv_disp_q': 'Fed SPF Non Residential Investment 1y (Dispersion P75 - P25) (%)', 'fed_spf_resinv_disp_q': 'Fed SPF Residential Investment 1y (Dispersion P75 - P25) (%)', 'fed_spf_unemp_disp_q': 'Fed SPF Unemployment 1y (Dispersion P75 - P25) (%)', 'fed_spf_cpi1y_disp_q': 'Fed SPF CPI 1y (Dispersion P75 - P25) (%)', 'fed_spf_cpi10y_disp_q': 'Fed SPF CPI 10y (Dispersion P75 - P25) (%)', 'ecb_spf_hcpi1y_median_q': 'ECB SPF HCPI 1y Median (%)', 'ecb_spf_hcpi2y_median_q': 'ECB SPF HCPI 2y Median (%)', 'ecb_spf_gdp1y_median_q': 'ECB SPF GDP 1y Median (%)', 'ecb_spf_gdp2y_median_q': 'ECB SPF GDP 2y Median (%)', 'ecb_spf_unemp1y_median_q': 'ECB SPF Unemployment 1y Median (%)', 'ecb_spf_unemp2y_median_q': 'ECB SPF Unemployment 2y Median (%)', 'ecb_spf_hcpi1y_disp_q': 'ECB SPF HCPI 1y Dispersion', 'ecb_spf_hcpi2y_disp_q': 'ECB SPF HCPI 2y Dispersion', 'ecb_spf_gdp1y_disp_q': 'ECB SPF GDP 1y Dispersion', 'ecb_spf_gdp2y_disp_q': 'ECB SPF GDP 2y Dispersion', 'ecb_spf_unemp1y_disp_q': 'ECB SPF Unemployment 1y Dispersion', 'ecb_spf_unemp2y_disp_q': 'ECB SPF Unemployment 2y Dispersion', 'em_curr_acc_usgdp_q': 'Emerging Countries Current Account (% US GDP)', 'em_curr_acc_ezgdp_q': 'Emerging Countries Current Account (% EZ GDP)'}

In [230]:
data

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,fed_sloos_ci_small_firms_tight_q,False,True,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
3,3,global_pmi_comp,False,True,Global PMI Composite (ZS),(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
5,5,jpm_vol,False,True,JPM FX Vol,NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
7,7,move,False,True,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
9,9,ted_spread_us,False,True,Ted Spread US (%),(0.0),(0.0),(0.0),(0.0),(0.058),NaN,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
11,11,vix,False,True,VIX SPX,NaN,NaN,NaN,NaN,(0.0),(0.0),(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
12,12,intercept,True,False,,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
13,13,intercept,False,True,,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,14,AIC,False,False,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [231]:
df_completo = data #usado posteriormente para criar a tabela 3 do ppt

In [232]:
df_coef = data[
    (data['coef'] == True) |
    ((data['pval'] == False) & (data['coef'] == False))
]

df_pval = data[
    (data['pval'] == True) |
    ((data['pval'] == False) & (data['coef'] == False))
]

display(df_coef)
display(df_pval)

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,12,intercept,True,False,,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,14,AIC,False,False,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
1,1,fed_sloos_ci_small_firms_tight_q,False,True,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,global_pmi_comp,False,True,Global PMI Composite (ZS),(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
5,5,jpm_vol,False,True,JPM FX Vol,NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
7,7,move,False,True,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
9,9,ted_spread_us,False,True,Ted Spread US (%),(0.0),(0.0),(0.0),(0.0),(0.058),NaN,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
11,11,vix,False,True,VIX SPX,NaN,NaN,NaN,NaN,(0.0),(0.0),(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
13,13,intercept,False,True,,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,14,AIC,False,False,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [233]:
# Seleciona as últimas 7 linhas de 'Codes' e atribui o mesmo valor a 'Names'
last_7_codes = df_coef['Codes'].iloc[-7:]
df_coef.loc[df_coef.index[-7:], 'Names'] = last_7_codes.values
df_pval.loc[df_pval.index[-7:], 'Names'] = last_7_codes.values

In [234]:
display(df_coef)
display(df_pval)

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,12,intercept,True,False,intercept,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,14,AIC,False,False,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
1,1,fed_sloos_ci_small_firms_tight_q,False,True,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,global_pmi_comp,False,True,Global PMI Composite (ZS),(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
5,5,jpm_vol,False,True,JPM FX Vol,NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
7,7,move,False,True,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
9,9,ted_spread_us,False,True,Ted Spread US (%),(0.0),(0.0),(0.0),(0.0),(0.058),NaN,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
11,11,vix,False,True,VIX SPX,NaN,NaN,NaN,NaN,(0.0),(0.0),(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
13,13,intercept,False,True,intercept,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,14,AIC,False,False,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [235]:
df_coef.drop(columns=['Unnamed: 0','Codes', 'coef', 'pval'], inplace=True)
df_pval.drop(columns=['Unnamed: 0','Codes', 'coef', 'pval'], inplace=True)

C:\Users\gabriel\AppData\Local\Temp\ipykernel_44172\2876614728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coef.drop(columns=['Unnamed: 0','Codes', 'coef', 'pval'], inplace=True)
C:\Users\gabriel\AppData\Local\Temp\ipykernel_44172\2876614728.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pval.drop(columns=['Unnamed: 0','Codes', 'coef', 'pval'], inplace=True)

In [236]:
display(df_coef)
display(df_pval)

,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,intercept,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
1,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Global PMI Composite (ZS),(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
5,JPM FX Vol,NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
7,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
9,Ted Spread US (%),(0.0),(0.0),(0.0),(0.0),(0.058),NaN,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
11,VIX SPX,NaN,NaN,NaN,NaN,(0.0),(0.0),(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
13,intercept,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [237]:
df_coef.insert(df_coef.columns.get_loc("Names"), "Signal", "")
df_coef

,Signal,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,,intercept,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [238]:
df_coef.columns

Index(['Signal', 'Names', 'CDX_US_HY_spread', 'CDX_US_HY_spread1',
       'CDX_US_HY_spread2', 'CDX_US_HY_spread3', 'CDX_US_HY_spread4',
       'CDX_US_HY_spread5', 'CDX_US_HY_spread6', 'CDX_US_HY_spread7',
       'CDX_US_HY_spread8', 'CDX_US_HY_spread9', 'CDX_US_HY_spread10',
       'CDX_US_HY_spread11', 'CDX_US_HY_spread12', 'CDX_US_HY_spread13',
       'CDX_US_HY_spread14', 'CDX_US_HY_spread15'],
      dtype='object')

In [239]:
# Renomear as colunas, mantendo "Signal" e "Names" intactas
new_columns = []

for col in df_coef.columns:
    if col.startswith("CDX_US_HY_spread"):
        # Extraia o número do final (ou 0 se não houver sufixo)
        suffix = col.replace("CDX_US_HY_spread", "")
        number = int(suffix) + 1 if suffix.isdigit() else 1
        new_columns.append(str(number))
    else:
        new_columns.append(col)

# Atribuir os novos nomes ao DataFrame
df_coef.columns = new_columns

In [240]:
new_columns = []

for col in df_pval.columns:
    if col.startswith("CDX_US_HY_spread"):
        # Extraia o número do final (ou 0 se não houver sufixo)
        suffix = col.replace("CDX_US_HY_spread", "")
        number = int(suffix) + 1 if suffix.isdigit() else 1
        new_columns.append(str(number))
    else:
        new_columns.append(col)

# Atribuir os novos nomes ao DataFrame
df_pval.columns = new_columns

In [241]:
output_path = '../excel/out/df_coef_exported.xlsx'
df_coef.to_excel(output_path, index=False)

output_path2 = '../excel/out/df_pval_exported.xlsx'
df_pval.to_excel(output_path2, index=False)

##Começando a tabela 3

In [242]:
df_completo = df_completo[df_completo['coef'] == True]
df_completo

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,12,intercept,True,False,,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112

In [243]:
import os
import pandas as pd
import logging

In [244]:
# Configura o logger
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s — %(levelname)s — %(message)s',
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger(__name__)

In [245]:
notebook_dir = os.getcwd()
file_path = os.path.abspath(
    os.path.join(notebook_dir, '..', 'excel', 'in', 'out_DB_D.xlsx')
)
try:
    df = pd.read_excel(file_path)
    logger.info(f"Arquivo lido com sucesso: {file_path}")
except Exception as e:
    logger.error(f"Falha ao ler o arquivo {file_path}: {e}")
    raise

2025-07-30 13:22:14,891 — INFO — Arquivo lido com sucesso: d:\assistente_pesquisa\pietcon.github.io\regressoes\cdx_us_hy\excel\in\out_DB_D.xlsx

In [246]:
df.head()

,date,2y_nom_ger,2y_nom_fra,2y_nom_net,2y_nom_ita,2y_nom_spa,2y_nom_por,2y_nom_eur_weig_all,2y_nom_spread_weig_eur_ger_all,2y_nom_spread_eur_ger,5y_nom_ger,5y_nom_fra,5y_nom_net,5y_nom_ita,5y_nom_spa,5y_nom_por,5y_nom_eur_weig_all,5y_nom_spread_weig_eur_ger_all,5y_nom_spread_eur_ger,10y_nom_ger,10y_nom_fra,10y_nom_net,10y_nom_ita,10y_nom_spa,10y_nom_por,10y_nom_eur_weig_all,10y_nom_spread_weig_eur_ger_all,10y_nom_spread_eur_ger,2y_nom_us,5y_nom_us,10y_nom_us,2y_nom_jp,5y_nom_jp,10y_nom_jp,2y_nom_spread_ger_us,5y_nom_spread_ger_us,10y_nom_spread_ger_us,ted_spread_eur,ted_spread_us,incl_2y10y_us,incl_2y10y_ger,3m_real_exante,5y5y_be_us,fed_funds,3m_nom_us,3m3m_nom_us,6m_nom_us,1y_nom_us,10y_real_us,10y_real_ger,usdjpy_1y_hedge_cost,usdjpy_3m_hedge_cost,usdeur_1y_hedge_cost,usdeur_3m_hedge_cost,avg_1y_hedge_cost,avg_3m_hedge_cost,jpy5y_dif_1y_cost,jpy5y_dif_3m_cost,eur5y_dif_1y_cost,eur5y_dif_3m_cost,avg5y_dif_1y_cost,avg5y_dif_3m_cost,jpy10y_dif_1y_cost,jpy10y_dif_3m_cost,eur10y_dif_1y_cost,eur10y_dif_3m_cost,avg10y_dif_1y_cost,avg10y_dif_3m_cost,CDX_US_IG_spread,CDX_US_HY_spread,CDX_EZ_IG_spread,CDX_EZ_HY_spread,vix,v2x,move,jpm_vol,fed_share_ust_wo_bills,fed_share_ust,liq_ratio,liq_ratio_wo_repo,ecb_qe_rt,ecb_corp_qe_rt,ecb_corp_qe_purch_rt,ecb_corp_qe_redemp_rt,nom_bal_us_gdp,prim_bal_us_gdp,global_pmi_comp_ZS,global_pmi_manuf_ZS,global_pmi_serv_ZS,ez_pmi_comp_ZS,ez_pmi_manuf_ZS,ez_pmi_serv_ZS,ism_manuf_ZS,ism_serv_ZS,jpm_fri_gdp_us_ZS,jpm_fri_cpi_us_ZS,payroll_us_1m,ip_manuf_us_1m,ret_sal_us_1m,ip_manuf_ez_1m,ret_sal_ez_1m,payroll_us_3m,ip_manuf_us_3m,ret_sal_us_3m,ip_manuf_ez_3m,ret_sal_ez_3m,payroll_us_6m,ip_manuf_us_6m,ret_sal_us_6m,ip_manuf_ez_6m,ret_sal_ez_6m,payroll_us_12m,ip_manuf_us_12m,ret_sal_us_12m,ip_manuf_ez_12m,ret_sal_ez_12m,payroll_us_vol_2y,ip_manuf_us_vol_2y,ret_sal_us_vol_2y,ip_manuf_ez_vol_2y,ret_sal_ez_vol_2y,payroll_us_vol_5y,ip_manuf_us_vol_5y,ret_sal_us_vol_5y,ip_manuf_ez_vol_5y,ret_sal_ez_vol_5y,cpi_us_trail_2y,cpi_core_us_trail_2y,pce_core_us_trail_2y,hcpi_ez_trail_2y,hcpi_core_ez_trail_2y,cpi_us_trail_5y,cpi_core_us_trail_5y,pce_core_us_trail_5y,hcpi_ez_trail_5y,hcpi_core_ez_trail_5y,cpi_us_vol_2y,cpi_core_us_vol_2y,pce_core_us_vol_2y,hcpi_ez_vol_2y,hcpi_core_ez_vol_2y,cpi_us_vol_5y,cpi_core_us_vol_5y,pce_core_us_vol_5y,hcpi_ez_vol_5y,hcpi_core_ez_vol_5y,ecb_sloos_cdt_std_3bck_q_ZS,ecb_sloos_cdt_std_3frw_q_ZS,ecb_sloos_cdt_dem_3bck_q_ZS,ecb_sloos_cdt_dem_3frw_q_ZS,fed_sloos_ci_large_firms_tight_q_ZS,fed_sloos_ci_small_firms_tight_q_ZS,bis_gli_int_claims_all_sec_gdp,bis_gli_int_claims_bank_sec_gdp,bis_gli_int_claims_non_bank_sec_gdp,bis_gli_cross_border_claims_priv_non_fin_sec_gdp,bis_gli_total_claims_priv_non_fin_sec_gdp,bis_gli_local_claims_priv_non_fin_sec_gdp,bis_gli_us_claims_priv_non_fin_sec_gdp,bis_gli_ez_claims_priv_non_fin_sec_gdp,output_gap_us_q,gdp_qoq_us_q,gdp_yoy_us_q,output_gap_ez_q,gdp_qoq_ez_q,gdp_yoy_ez_q,unemp_gap_us_q,gdp_us_trail_5y,gdp_us_vol_5y,gdp_ez_trail_5y,gdp_ez_vol_5y,spf_fed_gdp_10y_q,spf_fed_cpi_5y_q,spf_fed_cpi_10y_q,spf_fed_gdp_1y_q,fed_spf_payroll_disp_q,fed_spf_ip_disp_q,fed_spf_gdp1y_disp_q,fed_spf_pce_disp_q,fed_spf_nonresinv_disp_q,fed_spf_resinv_disp_q,fed_spf_unemp_disp_q,fed_spf_cpi1y_disp_q,fed_spf_cpi10y_disp_q,ecb_spf_hcpi1y_median_q,ecb_spf_hcpi2y_median_q,ecb_spf_gdp1y_median_q,ecb_spf_gdp2y_median_q,ecb_spf_unemp1y_median_q,ecb_spf_unemp2y_median_q,ecb_spf_hcpi1y_disp_q,ecb_spf_hcpi2y_disp_q,ecb_spf_gdp1y_disp_q,ecb_spf_gdp2y_disp_q,ecb_spf_unemp1y_disp_q,ecb_spf_unemp2y_disp_q,corp_fin_gap_3M_gdp_q,corp_fin_gap_12M_gdp_q,corp_fin_gap_3M_jpm_gdp_q,corp_fin_gap_12M_jpm_gdp_q,hh_debt_gdp_us_q,hh_debt_disp_inc_us_q,priv_debt_gdp_us_q,corp_debt_gdp_us_q,public_debt_gdp_us_q,public_inmkt_debt_gdp_us_q,em_cc_usgdp,em_cc_ezgdp
0,1980-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1980-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.107948,0.100063,0.099863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009010,NaN,NaN,0.063709,0.131028,NaN,NaN,0.113061,0.10436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1980-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.108487,0.100243,0.100768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008607,NaN,NaN,0.063709,0.130063,NaN,NaN,0.112971,0.10472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1980-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.108666,0.100967,0.101310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008204,NaN,NaN,0.063709,0.131028,NaN,NaN,0.113061,0.10472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.00006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1980-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.108666,0.100967,0.101310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008204,NaN,NaN,0.063709,0.131028,NaN,NaN,0.113061,0.10472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.00006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [247]:
#Pegar as colunas
cols = df.columns.tolist()
cols

['date',
 '2y_nom_ger',
 '2y_nom_fra',
 '2y_nom_net',
 '2y_nom_ita',
 '2y_nom_spa',
 '2y_nom_por',
 '2y_nom_eur_weig_all',
 '2y_nom_spread_weig_eur_ger_all',
 '2y_nom_spread_eur_ger',
 '5y_nom_ger',
 '5y_nom_fra',
 '5y_nom_net',
 '5y_nom_ita',
 '5y_nom_spa',
 '5y_nom_por',
 '5y_nom_eur_weig_all',
 '5y_nom_spread_weig_eur_ger_all',
 '5y_nom_spread_eur_ger',
 '10y_nom_ger',
 '10y_nom_fra',
 '10y_nom_net',
 '10y_nom_ita',
 '10y_nom_spa',
 '10y_nom_por',
 '10y_nom_eur_weig_all',
 '10y_nom_spread_weig_eur_ger_all',
 '10y_nom_spread_eur_ger',
 '2y_nom_us',
 '5y_nom_us',
 '10y_nom_us',
 '2y_nom_jp',
 '5y_nom_jp',
 '10y_nom_jp',
 '2y_nom_spread_ger_us',
 '5y_nom_spread_ger_us',
 '10y_nom_spread_ger_us',
 'ted_spread_eur',
 'ted_spread_us',
 'incl_2y10y_us',
 'incl_2y10y_ger',
 '3m_real_exante',
 '5y5y_be_us',
 'fed_funds',
 '3m_nom_us',
 '3m3m_nom_us',
 '6m_nom_us',
 '1y_nom_us',
 '10y_real_us',
 '10y_real_ger',
 'usdjpy_1y_hedge_cost',
 'usdjpy_3m_hedge_cost',
 'usdeur_1y_hedge_cost',
 'usdeur_3m_hedge_cost',
 'avg_1y_hedge_cost',
 'avg_3m_hedge_cost',
 'jpy5y_dif_1y_cost',
 'jpy5y_dif_3m_cost',
 'eur5y_dif_1y_cost',
 'eur5y_dif_3m_cost',
 'avg5y_dif_1y_cost',
 'avg5y_dif_3m_cost',
 'jpy10y_dif_1y_cost',
 'jpy10y_dif_3m_cost',
 'eur10y_dif_1y_cost',
 'eur10y_dif_3m_cost',
 'avg10y_dif_1y_cost',
 'avg10y_dif_3m_cost',
 'CDX_US_IG_spread',
 'CDX_US_HY_spread',
 'CDX_EZ_IG_spread',
 'CDX_EZ_HY_spread',
 'vix',
 'v2x',
 'move',
 'jpm_vol',
 'fed_share_ust_wo_bills',
 'fed_share_ust',
 'liq_ratio',
 'liq_ratio_wo_repo',
 'ecb_qe_rt',
 'ecb_corp_qe_rt',
 'ecb_corp_qe_purch_rt',
 'ecb_corp_qe_redemp_rt',
 'nom_bal_us_gdp',
 'prim_bal_us_gdp',
 'global_pmi_comp_ZS',
 'global_pmi_manuf_ZS',
 'global_pmi_serv_ZS',
 'ez_pmi_comp_ZS',
 'ez_pmi_manuf_ZS',
 'ez_pmi_serv_ZS',
 'ism_manuf_ZS',
 'ism_serv_ZS',
 'jpm_fri_gdp_us_ZS',
 'jpm_fri_cpi_us_ZS',
 'payroll_us_1m',
 'ip_manuf_us_1m',
 'ret_sal_us_1m',
 'ip_manuf_ez_1m',
 'ret_sal_ez_1m',
 'payroll_us_3m',
 'ip_manuf_us_3m',
 'ret_sal_us_3m',
 'ip_manuf_ez_3m',
 'ret_sal_ez_3m',
 'payroll_us_6m',
 'ip_manuf_us_6m',
 'ret_sal_us_6m',
 'ip_manuf_ez_6m',
 'ret_sal_ez_6m',
 'payroll_us_12m',
 'ip_manuf_us_12m',
 'ret_sal_us_12m',
 'ip_manuf_ez_12m',
 'ret_sal_ez_12m',
 'payroll_us_vol_2y',
 'ip_manuf_us_vol_2y',
 'ret_sal_us_vol_2y',
 'ip_manuf_ez_vol_2y',
 'ret_sal_ez_vol_2y',
 'payroll_us_vol_5y',
 'ip_manuf_us_vol_5y',
 'ret_sal_us_vol_5y',
 'ip_manuf_ez_vol_5y',
 'ret_sal_ez_vol_5y',
 'cpi_us_trail_2y',
 'cpi_core_us_trail_2y',
 'pce_core_us_trail_2y',
 'hcpi_ez_trail_2y',
 'hcpi_core_ez_trail_2y',
 'cpi_us_trail_5y',
 'cpi_core_us_trail_5y',
 'pce_core_us_trail_5y',
 'hcpi_ez_trail_5y',
 'hcpi_core_ez_trail_5y',
 'cpi_us_vol_2y',
 'cpi_core_us_vol_2y',
 'pce_core_us_vol_2y',
 'hcpi_ez_vol_2y',
 'hcpi_core_ez_vol_2y',
 'cpi_us_vol_5y',
 'cpi_core_us_vol_5y',
 'pce_core_us_vol_5y',
 'hcpi_ez_vol_5y',
 'hcpi_core_ez_vol_5y',
 'ecb_sloos_cdt_std_3bck_q_ZS',
 'ecb_sloos_cdt_std_3frw_q_ZS',
 'ecb_sloos_cdt_dem_3bck_q_ZS',
 'ecb_sloos_cdt_dem_3frw_q_ZS',
 'fed_sloos_ci_large_firms_tight_q_ZS',
 'fed_sloos_ci_small_firms_tight_q_ZS',
 'bis_gli_int_claims_all_sec_gdp',
 'bis_gli_int_claims_bank_sec_gdp',
 'bis_gli_int_claims_non_bank_sec_gdp',
 'bis_gli_cross_border_claims_priv_non_fin_sec_gdp',
 'bis_gli_total_claims_priv_non_fin_sec_gdp',
 'bis_gli_local_claims_priv_non_fin_sec_gdp',
 'bis_gli_us_claims_priv_non_fin_sec_gdp',
 'bis_gli_ez_claims_priv_non_fin_sec_gdp',
 'output_gap_us_q',
 'gdp_qoq_us_q',
 'gdp_yoy_us_q',
 'output_gap_ez_q',
 'gdp_qoq_ez_q',
 'gdp_yoy_ez_q',
 'unemp_gap_us_q',
 'gdp_us_trail_5y',
 'gdp_us_vol_5y',
 'gdp_ez_trail_5y',
 'gdp_ez_vol_5y',
 'spf_fed_gdp_10y_q',
 'spf_fed_cpi_5y_q',
 'spf_fed_cpi_10y_q',
 'spf_fed_gdp_1y_q',
 'fed_spf_payroll_disp_q',
 'fed_spf_ip_disp_q',
 'fed_spf_gdp1y_disp_q',
 'fed_spf_pce_disp_q',
 'fed_spf_nonresinv_disp_q',
 'fed_spf_resinv_disp_q',
 'fed_spf_unemp_disp_q',
 'fed_spf_cpi1y_disp_q',
 'fed_spf_cpi10y_disp_q',
 'ecb_spf_hcpi1y_median_q',
 'ecb_spf_hcpi2y_median_q',
 'ecb_spf_gdp1y_median_q',
 'ecb_spf_gdp2y_median_q',
 'ecb_spf_unemp1y_median_q',
 'ecb_spf_unemp2y_median_q',
 'ecb_spf_hcpi1y_disp_q',
 'ecb_spf_hcpi2y_disp_q',
 'ecb_spf_gdp1y_disp_q',
 'ecb_spf_gdp2y_disp_q',
 'ecb_spf_unemp1y_disp_q',
 'ecb_spf_unemp2y_disp_q',
 'corp_fin_gap_3M_gdp_q',
 'corp_fin_gap_12M_gdp_q',
 'corp_fin_gap_3M_jpm_gdp_q',
 'corp_fin_gap_12M_jpm_gdp_q',
 'hh_debt_gdp_us_q',
 'hh_debt_disp_inc_us_q',
 'priv_debt_gdp_us_q',
 'corp_debt_gdp_us_q',
 'public_debt_gdp_us_q',
 'public_inmkt_debt_gdp_us_q',
 'em_cc_usgdp',
 'em_cc_ezgdp']

In [248]:
comuns = list(set(df_completo['Codes'].tolist()) & set(cols))
comuns.insert(0, "date")
print(comuns)

['date', 'move', 'jpm_vol', 'vix', 'ted_spread_us']

In [249]:
df_filtered_serie = df.loc[df.index[-30:], comuns]
pd.set_option('display.max_rows', None)  # Mostra todas as linhas
pd.set_option('display.max_columns', None)  # Mostra todas as colunas
# Conta o número de linhas e colunas no dataframe
num_linhas, num_colunas = df_filtered_serie.shape

display(df_filtered_serie)

print(f"Número de linhas: {num_linhas}")
print(f"Número de colunas: {num_colunas}")

            date      move   jpm_vol       vix  ted_spread_us
16095 2024-01-25  0.722172  0.007482  0.013360       0.002230
16096 2024-01-26  0.694297  0.007432  0.013173       0.002198
16097 2024-01-27  0.694297  0.007432  0.013173       0.002198
16098 2024-01-28  0.694297  0.007432  0.013173       0.002198
16099 2024-01-29  0.724355  0.007532  0.013508       0.002130
16100 2024-01-30  0.714224  0.007532  0.013222       0.002078
16101 2024-01-31  0.728900  0.007631  0.014248       0.002087
16102 2024-02-01  0.760432  0.007581  0.013785       0.001671
16103 2024-02-02  0.726195  0.007611  0.013755       0.001799
16104 2024-02-03  0.726195  0.007611  0.013755       0.001799
16105 2024-02-04  0.726195  0.007611  0.013755       0.001799
16106 2024-02-05  0.735632  0.007720  0.013577       0.002035
16107 2024-02-06  0.744790  0.007621  0.012975       0.002080
16108 2024-02-07  0.731695  0.007541  0.012748       0.001937
16109 2024-02-08  0.735248  0.007442  0.012709       0.001768
16110 2024-02-09  0.723725  0.007283  0.012847       0.001875
16111 2024-02-10  0.723725  0.007283  0.012847       0.001875
16112 2024-02-11  0.723725  0.007283  0.012847       0.001875
16113 2024-02-12  0.740889  0.007134  0.013834       0.001760
16114 2024-02-13  0.757154  0.007214  0.015726       0.001754
16115 2024-02-14  0.751275  0.007214  0.014278       0.001951
16116 2024-02-15  0.751841  0.007075  0.013913       0.002005
16117 2024-02-16  0.738121  0.006946  0.014140       0.001964
16118 2024-02-17  0.738121  0.006946  0.014140       0.001964
16119 2024-02-18  0.738121  0.006946  0.014140       0.001964
16120 2024-02-19  0.738121  0.006876  0.014603       0.001964
16121 2024-02-20  0.746783  0.006767  0.015302       0.002161
16122 2024-02-21  0.762067  0.006717  0.015224       0.001854
16123 2024-02-22  0.768208  0.006648  0.014435       0.001784
16124 2024-02-23  0.768208  0.006648  0.013893       0.001814

Número de linhas: 30
Número de colunas: 5

In [250]:
delta_x = df_filtered_serie.iloc[-1] - df_filtered_serie.iloc[0]
print(delta_x)

date             29 days 00:00:00
move                     0.046036
jpm_vol                 -0.000834
vix                      0.000533
ted_spread_us           -0.000416
dtype: object

In [251]:
filtered_codes = df_completo[df_completo['Codes'].isin(comuns)]
filtered_codes = filtered_codes[['Codes', 'Names']]
display(filtered_codes)

            Codes              Names
4         jpm_vol         JPM FX Vol
6            move               MOVE
8   ted_spread_us  Ted Spread US (%)
10            vix            VIX SPX

In [252]:
# Cria dicionários para início, fim e delta
inicios_dict = {}
fins_dict = {}
deltas_dict = {}

# Itera sobre as variáveis filtradas dinamicamente
for code in filtered_codes['Codes']:
    if code in df_filtered_serie.columns:
        inicio = df_filtered_serie.iloc[0][code]
        fim = df_filtered_serie.iloc[-1][code]
        delta = fim - inicio
    else:
        inicio = fim = delta = None  # Caso a variável não esteja no df_filtered_serie
    
    inicios_dict[code] = inicio
    fins_dict[code] = fim
    deltas_dict[code] = delta

In [253]:
inicios_dict

{'jpm_vol': 0.007481940347755529,
 'move': 0.7221718596005616,
 'ted_spread_us': 0.002229512788283484,
 'vix': 0.01336035170183639}

In [ ]:
# Adiciona colunas ao DataFrame com base nos dicionáriosA
filtered_codes['inicio'] = filtered_codes['Codes'].map(inicios_dict)
filtered_codes['fim'] = filtered_codes['Codes'].map(fins_dict)
filtered_codes['delta'] = filtered_codes['Codes'].map(deltas_dict)

In [255]:
display(filtered_codes)

            Codes              Names    inicio       fim     delta
4         jpm_vol         JPM FX Vol  0.007482  0.006648 -0.000834
6            move               MOVE  0.722172  0.768208  0.046036
8   ted_spread_us  Ted Spread US (%)  0.002230  0.001814 -0.000416
10            vix            VIX SPX  0.013360  0.013893  0.000533

In [256]:
display(df_completo)

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,12,intercept,True,False,,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112

In [257]:
# Identifica colunas que começam com 'CDX_US_HY_spread'
coef_cols = [col for col in df_completo.columns if col.startswith('CDX_US_HY_spread')]

# Seleciona a linha do intercept
intercept_row = df_completo[df_completo['Codes'] == 'intercept']

# Cria o dicionário com chaves numéricas e valores do intercept
if not intercept_row.empty:
    intercept = {idx + 1: intercept_row.iloc[0][col] for idx, col in enumerate(coef_cols)}
else:
    intercept = {}

print(intercept)

{1: 0.0374, 2: 0.0381, 3: 0.0387, 4: -0.0145, 5: -0.0136, 6: -0.0145, 7: -0.0112, 8: -0.0107, 9: -0.0111, 10: -0.0108, 11: -0.009, 12: -0.0112, 13: -0.0112, 14: -0.0112, 15: -0.0112, 16: -0.0112}

In [258]:
coef_cols = [col for col in df_completo.columns if col.startswith('CDX_US_HY_spread')]
print("Colunas que começam com 'CDX_US_HY_spread':", coef_cols)

for i in range(len(filtered_codes)):
    code = filtered_codes.iloc[i]['Codes']
    delta = deltas_dict.get(code, None)

    if delta is not None:

        linha_completa = df_completo[df_completo['Codes'] == code]

        if not linha_completa.empty:
            for idx, col in enumerate(coef_cols, start=1): 
                coef_value = linha_completa.iloc[0][col]
                if pd.notna(coef_value):
                    filtered_codes.loc[filtered_codes.index[i], f'{idx}'] = coef_value * delta

Colunas que começam com 'CDX_US_HY_spread': ['CDX_US_HY_spread', 'CDX_US_HY_spread1', 'CDX_US_HY_spread2', 'CDX_US_HY_spread3', 'CDX_US_HY_spread4', 'CDX_US_HY_spread5', 'CDX_US_HY_spread6', 'CDX_US_HY_spread7', 'CDX_US_HY_spread8', 'CDX_US_HY_spread9', 'CDX_US_HY_spread10', 'CDX_US_HY_spread11', 'CDX_US_HY_spread12', 'CDX_US_HY_spread13', 'CDX_US_HY_spread14', 'CDX_US_HY_spread15']

In [259]:
filtered_codes

,Codes,Names,inicio,fim,delta,4,5,6,7,8,9,10,11,12,13,14,15,16,1,2,3
4,jpm_vol,JPM FX Vol,0.007482,0.006648,-0.000834,-0.004908,-0.003613,-0.003724,-0.003494,-0.003835,-0.003877,-0.003468,-0.003713,-0.003494,-0.003494,-0.003494,-0.003494,-0.003494,NaN,NaN,NaN
6,move,MOVE,0.722172,0.768208,0.046036,NaN,NaN,NaN,0.000497,0.000718,0.000764,0.000470,NaN,0.000497,0.000497,0.000497,0.000497,0.000497,NaN,NaN,NaN
8,ted_spread_us,Ted Spread US (%),0.002230,0.001814,-0.000416,-0.000289,-0.000141,NaN,NaN,-0.000070,NaN,-0.000051,-0.000078,NaN,NaN,NaN,NaN,NaN,-0.000656,-0.000666,-0.00051
10,vix,VIX SPX,0.013360,0.013893,0.000533,NaN,0.000419,0.000446,0.000226,NaN,NaN,0.000223,0.000262,0.000226,0.000226,0.000226,0.000226,0.000226,NaN,NaN,NaN

In [260]:
# Reorganiza o DataFrame
colunas_numericas = sorted([col for col in filtered_codes.columns if col.isdigit()], key=int)
colunas_fixas = [col for col in filtered_codes.columns if not col.isdigit()]
nova_ordem = colunas_fixas + colunas_numericas
filtered_codes = filtered_codes[nova_ordem]
filtered_codes

,Codes,Names,inicio,fim,delta,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
4,jpm_vol,JPM FX Vol,0.007482,0.006648,-0.000834,NaN,NaN,NaN,-0.004908,-0.003613,-0.003724,-0.003494,-0.003835,-0.003877,-0.003468,-0.003713,-0.003494,-0.003494,-0.003494,-0.003494,-0.003494
6,move,MOVE,0.722172,0.768208,0.046036,NaN,NaN,NaN,NaN,NaN,NaN,0.000497,0.000718,0.000764,0.000470,NaN,0.000497,0.000497,0.000497,0.000497,0.000497
8,ted_spread_us,Ted Spread US (%),0.002230,0.001814,-0.000416,-0.000656,-0.000666,-0.00051,-0.000289,-0.000141,NaN,NaN,-0.000070,NaN,-0.000051,-0.000078,NaN,NaN,NaN,NaN,NaN
10,vix,VIX SPX,0.013360,0.013893,0.000533,NaN,NaN,NaN,NaN,0.000419,0.000446,0.000226,NaN,NaN,0.000223,0.000262,0.000226,0.000226,0.000226,0.000226,0.000226

Calculo do Initial Pred
$$
\text{Initial Pred}_{25/01/2024} = \text{Intercept} + \beta_{\text{MOVE}} \times \text{MOVE} + \beta_{\text{JPM\_VOL}} \times \text{JPM\_VOL} + \beta_{\text{VIX}} \times \text{VIX} + \beta_{\text{TED}} \times \text{TED}
$$

In [261]:
df_filtered_serie

            date      move   jpm_vol       vix  ted_spread_us
16095 2024-01-25  0.722172  0.007482  0.013360       0.002230
16096 2024-01-26  0.694297  0.007432  0.013173       0.002198
16097 2024-01-27  0.694297  0.007432  0.013173       0.002198
16098 2024-01-28  0.694297  0.007432  0.013173       0.002198
16099 2024-01-29  0.724355  0.007532  0.013508       0.002130
16100 2024-01-30  0.714224  0.007532  0.013222       0.002078
16101 2024-01-31  0.728900  0.007631  0.014248       0.002087
16102 2024-02-01  0.760432  0.007581  0.013785       0.001671
16103 2024-02-02  0.726195  0.007611  0.013755       0.001799
16104 2024-02-03  0.726195  0.007611  0.013755       0.001799
16105 2024-02-04  0.726195  0.007611  0.013755       0.001799
16106 2024-02-05  0.735632  0.007720  0.013577       0.002035
16107 2024-02-06  0.744790  0.007621  0.012975       0.002080
16108 2024-02-07  0.731695  0.007541  0.012748       0.001937
16109 2024-02-08  0.735248  0.007442  0.012709       0.001768
16110 2024-02-09  0.723725  0.007283  0.012847       0.001875
16111 2024-02-10  0.723725  0.007283  0.012847       0.001875
16112 2024-02-11  0.723725  0.007283  0.012847       0.001875
16113 2024-02-12  0.740889  0.007134  0.013834       0.001760
16114 2024-02-13  0.757154  0.007214  0.015726       0.001754
16115 2024-02-14  0.751275  0.007214  0.014278       0.001951
16116 2024-02-15  0.751841  0.007075  0.013913       0.002005
16117 2024-02-16  0.738121  0.006946  0.014140       0.001964
16118 2024-02-17  0.738121  0.006946  0.014140       0.001964
16119 2024-02-18  0.738121  0.006946  0.014140       0.001964
16120 2024-02-19  0.738121  0.006876  0.014603       0.001964
16121 2024-02-20  0.746783  0.006767  0.015302       0.002161
16122 2024-02-21  0.762067  0.006717  0.015224       0.001854
16123 2024-02-22  0.768208  0.006648  0.014435       0.001784
16124 2024-02-23  0.768208  0.006648  0.013893       0.001814

In [262]:
print("Inícios:", inicios_dict)
print("Fins:", fins_dict)
print("Deltas:", deltas_dict)
print("Intercept", intercept)

Inícios: {'jpm_vol': 0.007481940347755529, 'move': 0.7221718596005616, 'ted_spread_us': 0.002229512788283484, 'vix': 0.01336035170183639}
Fins: {'jpm_vol': 0.006647853971464475, 'move': 0.7682082697818243, 'ted_spread_us': 0.001813754153032583, 'vix': 0.01389304318742333}
Deltas: {'jpm_vol': -0.0008340863762910534, 'move': 0.0460364101812627, 'ted_spread_us': -0.00041575863525090094, 'vix': 0.0005326914855869388}
Intercept {1: 0.0374, 2: 0.0381, 3: 0.0387, 4: -0.0145, 5: -0.0136, 6: -0.0145, 7: -0.0112, 8: -0.0107, 9: -0.0111, 10: -0.0108, 11: -0.009, 12: -0.0112, 13: -0.0112, 14: -0.0112, 15: -0.0112, 16: -0.0112}

In [263]:
coef_cols

['CDX_US_HY_spread',
 'CDX_US_HY_spread1',
 'CDX_US_HY_spread2',
 'CDX_US_HY_spread3',
 'CDX_US_HY_spread4',
 'CDX_US_HY_spread5',
 'CDX_US_HY_spread6',
 'CDX_US_HY_spread7',
 'CDX_US_HY_spread8',
 'CDX_US_HY_spread9',
 'CDX_US_HY_spread10',
 'CDX_US_HY_spread11',
 'CDX_US_HY_spread12',
 'CDX_US_HY_spread13',
 'CDX_US_HY_spread14',
 'CDX_US_HY_spread15']

In [264]:
# Mapeia os coef_cols para índices 1, 2, 3, ... para bater com o dicionário de intercept
coef_col_index_map = {col: idx+1 for idx, col in enumerate(coef_cols)}

# Inicializa dicionário de previsões
initial_preds = {}

# Loop por cada série (code)
for code in inicios_dict:
    inicio_val = inicios_dict[code]
    row = df_completo[df_completo['Codes'] == code]

    if row.empty:
        continue

    pred = 0.0
    for col in coef_cols:
        beta = row.iloc[0][col]
        if pd.notna(beta):
            pred += beta * inicio_val

            # Adiciona intercepto correspondente ao índice
            intercept_idx = coef_col_index_map[col]
            pred += intercept.get(intercept_idx, 0)

    initial_preds[code] = pred

print("Initial Predictions:", initial_preds)

Initial Predictions: {'jpm_vol': 0.28006629139226163, 'move': -0.02238317665081979, 'ted_spread_us': 0.06880205997582063, 'vix': -0.04724544577671334}

### Initial Prediction 
$$
\text{Initial Pred}_t = \sum_i \beta_{i,t} \cdot x_i(\text{inicio}) + \text{intercept}_t
$$

### Final Prediction
$$
\text{Final Pred}_t = \sum_i \beta_{i,t} \cdot x_i(\text{fim}) + \text{intercept}_t
$$

Aqui, você usa os `fins_dict` (valores finais) diretamente.

### Period Variation
$$
\text{Period Variation}_t = (\text{Final Pred}_t - \text{Initial Pred}_t) \times 100
$$

In [265]:
# Inicializa dicionário das previsões finais recalculadas
final_preds = {}

# Loop por cada série (code)
for code in fins_dict:
    fim_val = fins_dict[code]
    row = df_completo[df_completo['Codes'] == code]

    if row.empty:
        continue

    pred = 0.0
    for col in coef_cols:
        beta = row.iloc[0][col]
        if pd.notna(beta):
            pred += beta * fim_val

            # Adiciona intercepto da regressão correspondente
            intercept_idx = coef_col_index_map[col]
            pred += intercept.get(intercept_idx, 0)

    final_preds[code] = pred

print("Final Predictions (full):", final_preds)

Final Predictions (full): {'jpm_vol': 0.23196644847022196, 'move': -0.017448073479388433, 'ted_spread_us': 0.06634014521718244, 'vix': -0.04454001225971439}

In [266]:
# Inicializa dicionário de variação
period_variation = {}

for code in initial_preds:
    final_val = final_preds.get(code)
    initial_val = initial_preds[code]

    if final_val is not None:
        variation = (final_val - initial_val) * 100  # em pontos-base
        period_variation[code] = variation

print("Period Variation (bps):", period_variation)

Period Variation (bps): {'jpm_vol': -4.809984292203967, 'move': 0.49351031714313587, 'ted_spread_us': -0.24619147586381895, 'vix': 0.2705433516998951}

In [ ]:
df_result = pd.DataFrame([initial_preds, final_preds, period_variation],
                         index=['Initial Pred', 'FinalA Pred', 'Period Variation (bps)'])

df_result

                         jpm_vol      move  ted_spread_us       vix
Initial Pred            0.280066 -0.022383       0.068802 -0.047245
Final Pred              0.231966 -0.017448       0.066340 -0.044540
Period Variation (bps) -4.809984  0.493510      -0.246191  0.270543