In [1]:
import pandas as pd

# Read the Excel file
file_path = '../excel/out/US/Credit/HY/t_0/reccursive/sectors_regs_summary.xlsx'
data = pd.read_excel(file_path)

leg = pd.read_excel("../excel/in/legendas.xlsx")
# Display the first few rows of the dataframe
display(data.head())

,Unnamed: 0,idx,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q (coef),NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,f(pval),NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp (coef),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
3,3,g(pval),(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
4,4,jpm_vol (coef),NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886

In [2]:
data.rename(columns={"idx": "Codes"}, inplace=True)
data.insert(data.columns.get_loc("Codes") + 1, "Names", "")
display(data)

,Unnamed: 0,Codes,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q (coef),,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,f(pval),,NaN,(0.0),(0.0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp (coef),,-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
3,3,g(pval),,(0.0),NaN,(0.0),NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
4,4,jpm_vol (coef),,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
5,5,j(pval),,NaN,NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
6,6,move (coef),,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
7,7,m(pval),,NaN,NaN,NaN,NaN,NaN,NaN,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
8,8,ted_spread_us (coef),,1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
9,9,t(pval),,(0.0),(0.0),(0.0),(0.0),(0.058),NaN,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
10,10,vix (coef),,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
11,11,v(pval),,NaN,NaN,NaN,NaN,(0.0),(0.0),(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
12,12,intercept (coef),,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
13,13,i(pval),,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,14,AIC,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,MSE,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,R2,,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [3]:
data.insert(data.columns.get_loc("Codes") + 1, "coef", data['Codes'].str.endswith('(coef)'))
data.insert(data.columns.get_loc("Codes") + 2, "pval", data['Codes'].str.endswith('(pval)'))

In [4]:
for idx, i in data['coef'].items():
    if i == True:
        data.at[idx, 'Codes'] = data.at[idx, 'Codes'].replace(" (coef)", "")
        

for idx, i in data['pval'].items():
    if i == True:
        data.at[idx, 'Codes'] = data.at[idx - 1, 'Codes']

In [5]:
mapping = dict(zip(leg["Codes"], leg["Names"]))
print(mapping)

for idx, code in data["Codes"].items():
    if code in mapping:
        data.at[idx, "Names"] = mapping[code]

{'ted_spread_us': 'Ted Spread US (%)', 'ted_spread_eur': 'Ted Spread Europe (%)', 'fed_funds': 'Fed Funds (%)', '3m_nom_us': '3m Bill US (%)', '3m3m_nom_us': '3m3m Forward', '6m_nom_us': '6m Bill US (%)', '1y_nom_us': '1y Bill US (%)', '2y_nom_us': '2y Note US (%)', '5y_nom_us': '5y Note US (%)', '10y_nom_us': '10y Note US (%)', '10y_real_us': '10y TIPS (%)', '5y5y_be_us': '5Y5Y TIPS BE (%)', '3m_nom_ger': '3m Bill Germany (%)', '2y_nom_ger': '2y Note Germany (%)', '2y_nom_fra': '2y Note France (%)', '2y_nom_net': '2y Note Netherlands (%)', '2y_nom_ita': '2y Note Italy (%)', '2y_nom_spa': '2y Note Spain (%)', '2y_nom_por': '2y Note Portugal (%)', '5y_nom_ger': '5y Note Germany (%)', '5y_nom_fra': '5y Note France (%)', '5y_nom_net': '5y Note Netherlands (%)', '5y_nom_ita': '5y Note Italy (%)', '5y_nom_spa': '5y Note Spain (%)', '5y_nom_por': '5y Note Portugal (%)', '10y_nom_ger': '10y Note Germany (%)', '10y_nom_fra': '10y Note France (%)', '10y_nom_net': '10y Note Netherlands (%)', '10y_nom_ita': '10y Note Italy (%)', '10y_nom_spa': '10y Note Spain (%)', '10y_nom_por': '10y Note Portugal (%)', '2y_nom_eur_weig_all': '2y Nom Europe All weighted Agg (%)', '5y_nom_eur_weig_all': '5y Nom Europe All weighted Agg (%)', '10y_nom_eur_weig_all': '10y Nom Europe All weighted Agg (%)', '2y_nom_spread_weig_eur_ger_all': '2y Nom Europe Spread All Weighted Agg (%)', '5y_nom_spread_weig_eur_ger_all': '5y Nom Europe Spread All Weighted Agg (%)', '10y_nom_spread_weig_eur_ger_all': '10y Nom Europe Spread All Weighted Agg (%)', '2y_nom_spread_eur_ger': '2y Nom Europe Simple Spread All Agg (%)', '5y_nom_spread_eur_ger': '5y Nom Europe Simple Spread All Agg (%)', '10y_nom_spread_eur_ger': '10y Nom Europe Simple Spread All Agg (%)', '2y_nom_jp': '3y JGB (%)', '5y_nom_jp': '5y JGB (%)', '10y_nom_jp': '10y JGB (%)', '2y_nom_spread_ger_us': '2y Nom Spread GE-US (%)', '5y_nom_spread_ger_us': '5y Nom Spread GE-US (%)', '10y_nom_spread_ger_us': '10y Nom Spread GE-US (%)', 'incl_2y10y_us': '10y-2y Spread US (%)', 'incl_2y10y_ger': '10y-2y Spread Germany (%)', 'usdjpy_1y_hedge_cost': 'JPY Hedge Cost 1y (% aa)', 'usdjpy_3m_hedge_cost': 'JPY Hedge Cost 3m (% aa)', 'usdeur_1y_hedge_cost': 'EUR Hedge Cost 1y (% aa)', 'usdeur_3m_hedge_cost': 'EUR Hedge Cost 3m (% aa)', 'avg_1y_hedge_cost': 'Average Hedge Cost 1y (% aa)', 'avg_3m_hedge_cost': 'Average Hedge Cost 3m (% aa)', 'jpy5y_dif_1y_cost': 'JPY 5y diff (-) Hedge cost 1y', 'jpy5y_dif_3m_cost': 'JPY 5y diff (-) Hedge cost 3m', 'eur5y_dif_1y_cost': 'EUR 5y diff (-) Hedge cost 1y', 'eur5y_dif_3m_cost': 'EUR 5y diff (-) Hedge cost 3m', 'avg5y_dif_1y_cost': 'AVG 5y diff (-) Hedge cost 1y', 'avg5y_dif_3m_cost': 'AVG 5y diff (-) Hedge cost 3m', 'jpy10y_dif_1y_cost': 'JPY 10y diff (-) Hedge cost 1y', 'jpy10y_dif_3m_cost': 'JPY 10y diff (-) Hedge cost 3m', 'eur10y_dif_1y_cost': 'EUR 10y diff (-) Hedge cost 1y', 'eur10y_dif_3m_cost': 'EUR 10y diff (-) Hedge cost 3m', 'avg10y_dif_1y_cost': 'AVG 10y diff (-) Hedge cost 1y', 'avg10y_dif_3m_cost': 'AVG 10y diff (-) Hedge cost 3m', '10y_real_ger': '10y Real Note Germany (%)', 'usdjpy': 'USDJPY', 'eurusd': 'EURUSD', 'CDX_US_IG_spread': 'CDX IG US Index', 'CDX_US_HY_spread': 'CDX HY US Index', 'CDX_EZ_IG_spread': 'CDX IG BBG', 'CDX_EZ_HY_spread': 'CDX HY BBG', 'vix': 'VIX SPX', 'v2x': 'VIX Eurostoxx', 'jpm_vol': 'JPM FX Vol', 'move': 'MOVE', 'wti': 'WTI', 'liq_ratio': 'Ratio: (Fed Excess reserves + Reverse Repos) to (Treasuries and Notes outside the Fed)', 'liq_ratio_wo_repo': 'Ratio: (Fed Excess reserves) to (Treasuries and Notes outside the Fed)', 'fed_share_ust_wo_bills': 'Fed Share of UST Market w/o Bills (%)', 'fed_share_ust': 'Fed Share of UST Market (%)', 'ecb_qe_rt': 'Ratio to GDP: ECB Securities of Euro Residents Denominated in Euro Balance', 'ecb_corp_qe_rt': 'Ratio to GDP: ECB Corp Sector Purchase Balance', 'ecb_corp_qe_purch_rt': 'Ratio to GDP: ECB Corp Sector Purchase Programme Weekly Purchases', 'ecb_corp_qe_redemp_rt': 'Ratio to GDP: ECB Corp Sector Purchase Programme Weekly Redemptions', 'ez_pmi_comp_ZS': 'Eurozone Composite PMI SA (ZS)', 'ez_pmi_manuf_ZS': 'Eurozone Manufacturing PMI SA (ZS)', 'ez_pmi_serv_ZS': 'Eurozone Services PMI SA (ZS)', 'ism_manuf_ZS': 'ISM Manufacturing (ZS)', 'ism_serv_ZS': 'ISM Service (ZS)', 'global_pmi_comp': 'Global PMI Composite (ZS)', 'global_pmi_comp_ZS': 'Global PMI Composite (ZS)', 'global_pmi_manuf_ZS': 'Global PMI Manufacturing (ZS)', 'global_pmi_serv_ZS': 'Global PMI Service (ZS)', 'payroll_us_1m': 'Payroll (1m %chg)', 'ip_manuf_us_1m': 'US Industrial Production SA (1m %chg)', 'ret_sal_us_1m': 'US Retail Sales SA (1m %chg)', 'ip_manuf_ez_1m': 'Eurostat Industrial Production Eurozone SWDA (1m %chg)', 'ret_sal_ez_1m': 'Eurostat Retail Sales Volume Eurozone SWDA (1m %chg)', 'payroll_us_3m': 'Payroll (3m %chg)', 'ip_manuf_us_3m': 'US Industrial Production SA (3m %ave chg)', 'ret_sal_us_3m': 'US Retail Sales SA (3m %ave chg)', 'ip_manuf_ez_3m': 'Eurostat Industrial Production Eurozone SWDA (3m %ave chg)', 'ret_sal_ez_3m': 'Eurostat Retail Sales Volume Eurozone SWDA (3m %ave chg)', 'payroll_us_6m': 'Payroll (6m %ave chg)', 'ip_manuf_us_6m': 'US Industrial Production SA (6m %ave chg)', 'ret_sal_us_6m': 'US Retail Sales SA (6m %ave chg)', 'ip_manuf_ez_6m': 'Eurostat Industrial Production Eurozone SWDA (6m %ave chg)', 'ret_sal_ez_6m': 'Eurostat Retail Sales Volume Eurozone SWDA (6m %ave chg)', 'payroll_us_12m': 'Payroll (12m %ave chg)', 'ip_manuf_us_12m': 'US Industrial Production SA (12m %ave chg)', 'ret_sal_us_12m': 'US Retail Sales SA (12m %ave chg)', 'ip_manuf_ez_12m': 'Eurostat Industrial Production Eurozone SWDA (12m %ave chg)', 'ret_sal_ez_12m': 'Eurostat Retail Sales Volume Eurozone SWDA (12m %ave chg)', 'payroll_us_vol_2y': 'Payroll (3m %ave chg, 2y vol)', 'ip_manuf_us_vol_2y': 'US Industrial Production SA (3m %ave chg, 2y vol)', 'ret_sal_us_vol_2y': 'US Retail Sales SA (3m %ave chg, 2y vol)', 'ip_manuf_ez_vol_2y': 'Eurostat Industrial Production Eurozone SWDA (3m %ave chg, 2y vol)', 'ret_sal_ez_vol_2y': 'Eurostat Retail Sales Volume Eurozone SWDA (3m %ave chg, 2y vol)', 'payroll_us_vol_5y': 'Payroll (3m %ave chg, 5y vol)', 'ip_manuf_us_vol_5y': 'US Industrial Production SA (3m %ave chg, 5y vol)', 'ret_sal_us_vol_5y': 'US Retail Sales SA (3m %ave chg, 5y vol)', 'ip_manuf_ez_vol_5y': 'Eurostat Industrial Production Eurozone SWDA (3m %ave chg, 5y vol)', 'ret_sal_ez_vol_5y': 'Eurostat Retail Sales Volume Eurozone SWDA (3m %ave chg, 5y vol)', 'cpi_us_trail_2y': 'US CPI Urban Consumers (YoY, 2y average)', 'cpi_core_us_trail_2y': 'US CPI Urban Consumers Less Food & Energy (YoY, 2y average)', 'pce_core_us_trail_2y': 'US Core PCE Core Price Index (YoY, 2y average)', 'hcpi_ez_trail_2y': 'Euro Area CPI (YoY, 2y average)', 'hcpi_core_ez_trail_2y': 'Euro Area Core CPI (YoY, 2y average)', 'cpi_us_trail_5y': 'US CPI Urban Consumers (YoY, 5y average)', 'cpi_core_us_trail_5y': 'US CPI Urban Consumers Less Food & Energy (YoY, 5y average)', 'pce_core_us_trail_5y': 'US Core PCE Core Price Index (YoY, 5y average)', 'hcpi_ez_trail_5y': 'Euro Area CPI (YoY, 5y average)', 'hcpi_core_ez_trail_5y': 'Euro Area Core CPI (YoY, 5y average)', 'cpi_us_vol_2y': 'US CPI Urban Consumers (YoY, 2y vol)', 'cpi_core_us_vol_2y': 'US CPI Urban Consumers Less Food & Energy (YoY, 2y vol)', 'pce_core_us_vol_2y': 'US Core PCE Core Price Index (YoY, 2y vol)', 'hcpi_ez_vol_2y': 'Euro Area CPI (YoY, 2y vol)', 'hcpi_core_ez_vol_2y': 'Euro Area Core CPI (YoY, 2y vol)', 'cpi_us_vol_5y': 'US CPI Urban Consumers (YoY, 5y vol)', 'cpi_core_us_vol_5y': 'US CPI Urban Consumers Less Food & Energy (YoY, 5y vol)', 'pce_core_us_vol_5y': 'US Core PCE Core Price Index (YoY, 5y vol)', 'hcpi_ez_vol_5y': 'Euro Area CPI (YoY, 5y vol)', 'hcpi_core_ez_vol_5y': 'Euro Area Core CPI (YoY, 5y vol)', 'us_revenue_m': 'US Treasury Revenue (Bi) (Montlhy)', 'us_expenditures_m': 'US Treasury Expenditure (Bi) (Montlhy)', 'us_interest_m': 'US Treasury Net Interest (Bi) (Montlhy)', 'us_treas_bill': 'US Debt Held by the Public Outstanding Bills (Mi)', 'us_treas_note': 'US Debt Held by the Public Outstanding Notes (Mi)', 'us_treas_bond': 'US Debt Held by the Public Outstanding Bonds (Mi)', 'jpm_fri_gdp_us_ZS': 'JPMorgan GDP Forecast Revision Index US (ZS)', 'jpm_fri_cpi_us_ZS': 'JPMorgan CPI Forecast Revision Index US (ZS)', 'bbg_cdx_us_hy_tot_out': 'BBG HY Index Outstanding - Total', 'bbg_cdx_us_hy_BA_out': 'BBG HY Index Outstanding - BA Rating', 'bbg_cdx_us_hy_B_out': 'BBG HY Index Outstanding - B Rating', 'bbg_cdx_us_hy_CAA_out': 'BBG HY Index Outstanding - CAA Rating', 'bbg_cdx_us_hy_CAA_minus': 'BBG HY Index Outstanding - Below CAA Rating', 'credit_hh_ez': 'ECB Euro Area MFI Loans to Households Outstanding', 'credit_nonfin_corp_ez': 'ECB Euro Area MFI Loans to Non-Financial Corp Outstanding', 'output_gap_us_q': 'CBO US Real Output Gap (% GDP)', 'unemp_nat_us_q': 'CBO Natural Rate of Unemp. (%)', 'gdp_nom_us_q': 'GDP US Nominal (Bi) Dollars SAAR', 'gdp_cte_us_q': 'GDP US Chained 2012 (Bi) Dollars SAAR', 'gdp_qoq_us_q': 'GDP US Chained 2012 Dollars QoQ SA (%)', 'gdp_yoy_us_q': 'GDP US Chained 2012 Dollars YoY SA (%)', 'unemp_us_q': 'US Unemployment Rate (%)', 'spf_fed_gdp_y0_q': 'Fed SPF GDP Price Index SA Curr Year (Bi)', 'spf_fed_gdp_y1_q': 'Fed SPF GDP Price Index SA Curr Year +1 (Bi)', 'spf_fed_gdp_y2_q': 'Fed SPF GDP Price Index SA Curr Year +2 (Bi)', 'spf_fed_gdp_y3_q': 'Fed SPF GDP Price Index SA Curr Year +3 (Bi)', 'spf_fed_gdp_10y_q': 'Fed SPF 10Y GDP Growth', 'spf_fed_cpi_thisy_q': 'Fed SPF CPI SAAR Curr Year', 'spf_fed_cpi_nexty_q': 'Fed SPF CPI SAAR Curr Year +1', 'spf_fed_cpi_5y_q': 'Fed SPF 5Y CPI Inflation Rate', 'spf_fed_cpi_10y_q': 'Fed SPF 10Y CPI Inflation Rate', 'fed_sloos_ci_large_firms_tight_ZS': 'Fed Sloos Tight Std for C&I Loans (L&M-Market Firms) (ZS) (Smoothed)', 'fed_sloos_ci_small_firms_tight_q': 'Fed Sloos Tight Std for C&I Loans (Small Firms) (ZS) (Smoothed)', 'fed_sloos_ci_small_firms_tight_ZS': 'Fed Sloos Tight Std for C&I Loans (Small Firms) (ZS) (Smoothed)', 'ecb_sloos_cdt_std_3bck_ZS': 'ECB SLOOS Ave Net Lending All change 3m backward (ZS) (Smoothed)', 'ecb_sloos_cdt_std_3frw_ZS': 'ECB SLOOS Ave Net Lending All expected change 3m forward (ZS) (Smoothed)', 'ecb_sloos_cdt_dem_3bck_ZS': 'ECB SLOOS Ave Net Lending All change in demand 3m backward (ZS) (Smoothed)', 'ecb_sloos_cdt_dem_3frw_ZS': 'ECB SLOOS Ave Net Lending All expected change in demand 3m forward (ZS) (Smoothed)', 'corp_fin_gap_3M_gdp_q': 'Corporate Financing Gap (% GDP) (Smoothed)', 'corp_fin_gap_12M_gdp_q': 'Corporate Financing Gap (12M) (% GDP) (Smoothed)', 'corp_fin_gap_3M_jpm_gdp_q': 'Corporate Financing Gap JPM (% GDP) (Smoothed)', 'corp_fin_gap_12M_jpm_gdp': 'Corporate Financing Gap JPM (12M) (% GDP) (Smoothed)', 'hh_debt_gdp_us_q': 'Household Debt US (% GDP)', 'hh_debt_disp_inc_us_q': 'Household Debt US (% Disposable Income)', 'priv_debt_gdp_us_q': 'Private Debt US (% GDP)', 'corp_debt_gdp_us_q': 'Corporate Debt US (% GDP)', 'public_debt_gdp_us_q': 'Public Debt US (% GDP)', 'public_inmkt_debt_gdp_us_q': 'Public Debt in the Market US (% GDP)', 'gdp_nom_ez_q': 'GDP EMU Nominal (Mi) Euros SAAR', 'gdp_cte_ez_q': 'GDP EMU Chained 2012 (Mi) Euros SAAR', 'gdp_qoq_ez_q': 'GDP EMU Chained 2012 Dollars QoQ SA (%)', 'gdp_yoy_ez_q': 'GDP EMU Chained 2012 Dollars YoY SA (%)', 'output_gap_ez_q': 'BBG Euro Area Output Gap (%)', 'disp_inc_ez_q': 'EZ Gross Disposable Income (Bi)', 'gdp_nom_ger_q': 'Germany Nominal GDP (Bi)', 'gdp_nom_fra_q': 'France Nominal GDP (Bi)', 'gdp_nom_net_q': 'Netherlands Nominal GDP (Bi)', 'gdp_nom_ita_q': 'Italy Nominal GDP (Bi)', 'gdp_nom_spa_q': 'Spain Nominal GDP (Bi)', 'gdp_nom_por_q': 'Portugal Nominal GDP (Bi)', 'gdp_nom_ire_q': 'Ireland Nominal GDP (Bi)', 'debt_gdp_nom_ez_q': 'Eurozone Debt to GDP (%)', 'debt_gdp_nom_ger_q': 'Germany Debt to GDP (%)', 'debt_gdp_nom_fra_q': 'France Debt to GDP (%)', 'debt_gdp_nom_net_q': 'Netherlands Debt to GDP (%)', 'debt_gdp_nom_ita_q': 'Italy Debt to GDP (%)', 'debt_gdp_nom_spa_q': 'Spain Debt to GDP (%)', 'debt_gdp_nom_por_q': 'Portugal Debt to GDP (%)', 'debt_gdp_nom_ire_q': 'Ireland Debt to GDP (%)', 'spf_ecb_cpi_5y_q': 'ECB SPF HCPI 5 Years Ahead', 'spf_ecb_gdp_5y_q': 'ECB SPF GDP Growth 5 Years Ahead', 'bis_gli_int_claims_all_sec_gdp': 'BIS GLI International Claims on all Sectors (% GDP)', 'bis_gli_int_claims_bank_sec_gdp': 'BIS GLI International Claims on the Bank Sector (% GDP)', 'bis_gli_int_claims_non_bank_sec_gdp': 'BIS GLI International Claims on the Non-Bank Sectors (% GDP)', 'bis_gli_cross_border_claims_priv_non_fin_sec_gdp': 'BIS GLI Total Claims on Private Non-Financial Sector (% GDP)', 'bis_gli_total_claims_priv_non_fin_sec_gdp': 'BIS GLI Local Claims on Private Non-Financial Sector (% GDP)', 'bis_gli_local_claims_priv_non_fin_sec_gdp': 'BIS GLI Cross-Border Claims on Private Non-Financial Sector (% GDP)', 'bis_gli_us_claims_priv_non_fin_sec_gdp': 'BIS GLI Claims on US Private Non-Financial Sector (% GDP)', 'bis_gli_ez_claims_priv_non_fin_sec_gdp': 'BIS GLI Claims on EZ Private Non-Financial Sector (% GDP)', 'bis_gli_int_claims_all_sec_yoy': 'BIS GLI International Claims on all Sectors (YoY)', 'bis_gli_int_claims_bank_sec_yoy': 'BIS GLI International Claims on the Bank Sector (YoY)', 'bis_gli_int_claims_non_bank_sec_yoy': 'BIS GLI International Claims on the Non-Bank Sectors (YoY)', 'bis_gli_cross_border_claims_priv_non_fin_sec_yoy': 'BIS GLI Total Claims on Private Non-Financial Sector (YoY)', 'bis_gli_total_claims_priv_non_fin_sec_yoy': 'BIS GLI Local Claims on Private Non-Financial Sector (YoY)', 'bis_gli_local_claims_priv_non_fin_sec_yoy': 'BIS GLI Cross-Border Claims on Private Non-Financial Sector (YoY)', 'bis_gli_us_claims_priv_non_fin_sec_yoy': 'BIS GLI Claims on US Private Non-Financial Sector (YoY)', 'bis_gli_ez_claims_priv_non_fin_sec_yoy': 'BIS GLI Claims on EZ Private Non-Financial Sector (YoY)', 'fed_spf_payroll_disp_q': 'Fed SPF Payroll 1y (Dispersion P75 - P25) (%)', 'fed_spf_ip_disp_q': 'Fed SPF Industrial Production 1y (Dispersion P75 - P25) (%)', 'fed_spf_gdp1y_disp_q': 'Fed SPF GDP 1y (Dispersion P75 - P25) (%)', 'fed_spf_pce_disp_q': 'Fed SPF PCE 1y (Dispersion P75 - P25) (%)', 'fed_spf_nonresinv_disp_q': 'Fed SPF Non Residential Investment 1y (Dispersion P75 - P25) (%)', 'fed_spf_resinv_disp_q': 'Fed SPF Residential Investment 1y (Dispersion P75 - P25) (%)', 'fed_spf_unemp_disp_q': 'Fed SPF Unemployment 1y (Dispersion P75 - P25) (%)', 'fed_spf_cpi1y_disp_q': 'Fed SPF CPI 1y (Dispersion P75 - P25) (%)', 'fed_spf_cpi10y_disp_q': 'Fed SPF CPI 10y (Dispersion P75 - P25) (%)', 'ecb_spf_hcpi1y_median_q': 'ECB SPF HCPI 1y Median (%)', 'ecb_spf_hcpi2y_median_q': 'ECB SPF HCPI 2y Median (%)', 'ecb_spf_gdp1y_median_q': 'ECB SPF GDP 1y Median (%)', 'ecb_spf_gdp2y_median_q': 'ECB SPF GDP 2y Median (%)', 'ecb_spf_unemp1y_median_q': 'ECB SPF Unemployment 1y Median (%)', 'ecb_spf_unemp2y_median_q': 'ECB SPF Unemployment 2y Median (%)', 'ecb_spf_hcpi1y_disp_q': 'ECB SPF HCPI 1y Dispersion', 'ecb_spf_hcpi2y_disp_q': 'ECB SPF HCPI 2y Dispersion', 'ecb_spf_gdp1y_disp_q': 'ECB SPF GDP 1y Dispersion', 'ecb_spf_gdp2y_disp_q': 'ECB SPF GDP 2y Dispersion', 'ecb_spf_unemp1y_disp_q': 'ECB SPF Unemployment 1y Dispersion', 'ecb_spf_unemp2y_disp_q': 'ECB SPF Unemployment 2y Dispersion', 'em_curr_acc_usgdp_q': 'Emerging Countries Current Account (% US GDP)', 'em_curr_acc_ezgdp_q': 'Emerging Countries Current Account (% EZ GDP)'}

In [6]:
data

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,...,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,fed_sloos_ci_small_firms_tight_q,False,True,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,(0.0),(0.0),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,...,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
3,3,global_pmi_comp,False,True,Global PMI Composite (ZS),(0.0),NaN,(0.0),NaN,NaN,...,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,...,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
5,5,jpm_vol,False,True,JPM FX Vol,NaN,NaN,NaN,(0.0),(0.0),...,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,...,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
7,7,move,False,True,MOVE,NaN,NaN,NaN,NaN,NaN,...,(0.026),(0.001),(0.0),(0.04),NaN,(0.026),(0.026),(0.026),(0.026),(0.026)
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,...,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
9,9,ted_spread_us,False,True,Ted Spread US (%),(0.0),(0.0),(0.0),(0.0),(0.058),...,NaN,(0.344),NaN,(0.479),(0.279),NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,...,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
11,11,vix,False,True,VIX SPX,NaN,NaN,NaN,NaN,(0.0),...,(0.0),NaN,NaN,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
12,12,intercept,True,False,,0.0374,0.0381,0.0387,-0.0145,-0.0136,...,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
13,13,intercept,False,True,,(0.0),(0.0),(0.0),(0.0),(0.0),...,(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0),(0.0)
14,14,AIC,False,False,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,...,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,...,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,,0.2,0.19,0.2,0.37,0.46,...,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,,0.45,0.42,0.5,0.72,0.77,...,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [7]:
df_coef = data[
    (data['coef'] == True) |
    ((data['pval'] == False) & (data['coef'] == False))
]
df_coef

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,...,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,...,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,...,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,...,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,...,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,...,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,12,intercept,True,False,,0.0374,0.0381,0.0387,-0.0145,-0.0136,...,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,14,AIC,False,False,,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,...,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,...,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,,0.2,0.19,0.2,0.37,0.46,...,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,,0.45,0.42,0.5,0.72,0.77,...,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [8]:
# Seleciona as últimas 7 linhas de 'Codes' e atribui o mesmo valor a 'Names'
last_7_codes = df_coef['Codes'].iloc[-7:]
df_coef.loc[df_coef.index[-7:], 'Names'] = last_7_codes.values

In [9]:
df_coef

,Unnamed: 0,Codes,coef,pval,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,...,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,0,fed_sloos_ci_small_firms_tight_q,True,False,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,global_pmi_comp,True,False,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,...,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,4,jpm_vol,True,False,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,...,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,6,move,True,False,MOVE,NaN,NaN,NaN,NaN,NaN,...,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,8,ted_spread_us,True,False,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,...,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,10,vix,True,False,VIX SPX,NaN,NaN,NaN,NaN,0.7874,...,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,12,intercept,True,False,intercept,0.0374,0.0381,0.0387,-0.0145,-0.0136,...,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,14,AIC,False,False,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,...,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,15,BIC,False,False,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,...,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,16,DW,False,False,DW,0.2,0.19,0.2,0.37,0.46,...,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,17,LMpv,False,False,LMpv,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,MSE,False,False,MSE,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,19,R2,False,False,R2,0.45,0.42,0.5,0.72,0.77,...,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [10]:
df_coef.drop(columns=['Unnamed: 0','Codes', 'coef', 'pval'], inplace=True)

C:\Users\gabriel\AppData\Local\Temp\ipykernel_14092\987608591.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coef.drop(columns=['Unnamed: 0','Codes', 'coef', 'pval'], inplace=True)

In [12]:
df_coef

,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,intercept,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [13]:
df_coef.insert(df_coef.columns.get_loc("Names"), "Signal", "")
df_coef

,Signal,Names,CDX_US_HY_spread,CDX_US_HY_spread1,CDX_US_HY_spread2,CDX_US_HY_spread3,CDX_US_HY_spread4,CDX_US_HY_spread5,CDX_US_HY_spread6,CDX_US_HY_spread7,CDX_US_HY_spread8,CDX_US_HY_spread9,CDX_US_HY_spread10,CDX_US_HY_spread11,CDX_US_HY_spread12,CDX_US_HY_spread13,CDX_US_HY_spread14,CDX_US_HY_spread15
0,,Fed Sloos Tight Std for C&I Loans (Small Firms...,NaN,0.7177,0.4396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,Global PMI Composite (ZS),-0.8248,NaN,-0.6054,NaN,NaN,NaN,-0.3836,-0.5016,-0.517,-0.3742,-0.3422,-0.3836,-0.3836,-0.3836,-0.3836,-0.3836
4,,JPM FX Vol,NaN,NaN,NaN,5.8846,4.3313,4.4646,4.1886,4.5978,4.6482,4.1581,4.4515,4.1886,4.1886,4.1886,4.1886,4.1886
6,,MOVE,NaN,NaN,NaN,NaN,NaN,NaN,0.0108,0.0156,0.0166,0.0102,NaN,0.0108,0.0108,0.0108,0.0108,0.0108
8,,Ted Spread US (%),1.579,1.6022,1.2277,0.6954,0.3389,NaN,NaN,0.1682,NaN,0.1232,0.1869,NaN,NaN,NaN,NaN,NaN
10,,VIX SPX,NaN,NaN,NaN,NaN,0.7874,0.8369,0.424,NaN,NaN,0.4181,0.4924,0.424,0.424,0.424,0.424,0.424
12,,intercept,0.0374,0.0381,0.0387,-0.0145,-0.0136,-0.0145,-0.0112,-0.0107,-0.0111,-0.0108,-0.009,-0.0112,-0.0112,-0.0112,-0.0112,-0.0112
14,,AIC,-1499.66,-1484.17,-1519.98,-1678.92,-1732.18,-1730.54,-1761.07,-1748.69,-1749.77,-1759.58,-1757.24,-1761.07,-1761.07,-1761.07,-1761.07,-1761.07
15,,BIC,-1488.94,-1473.45,-1505.67,-1668.19,-1717.88,-1719.81,-1743.19,-1730.81,-1735.47,-1738.13,-1739.36,-1743.19,-1743.19,-1743.19,-1743.19,-1743.19
16,,DW,0.2,0.19,0.2,0.37,0.46,0.44,0.43,0.42,0.41,0.43,0.44,0.43,0.43,0.43,0.43,0.43
17,,LMpv,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,,MSE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,,R2,0.45,0.42,0.5,0.72,0.77,0.77,0.8,0.79,0.79,0.8,0.8,0.8,0.8,0.8,0.8,0.8

In [15]:
df_coef.columns

Index(['Signal', 'Names', 'CDX_US_HY_spread', 'CDX_US_HY_spread1',
       'CDX_US_HY_spread2', 'CDX_US_HY_spread3', 'CDX_US_HY_spread4',
       'CDX_US_HY_spread5', 'CDX_US_HY_spread6', 'CDX_US_HY_spread7',
       'CDX_US_HY_spread8', 'CDX_US_HY_spread9', 'CDX_US_HY_spread10',
       'CDX_US_HY_spread11', 'CDX_US_HY_spread12', 'CDX_US_HY_spread13',
       'CDX_US_HY_spread14', 'CDX_US_HY_spread15'],
      dtype='object')

In [16]:
# Renomear as colunas, mantendo "Signal" e "Names" intactas
new_columns = []

for col in df_coef.columns:
    if col.startswith("CDX_US_HY_spread"):
        # Extraia o número do final (ou 0 se não houver sufixo)
        suffix = col.replace("CDX_US_HY_spread", "")
        number = int(suffix) + 1 if suffix.isdigit() else 1
        new_columns.append(str(number))
    else:
        new_columns.append(col)

# Atribuir os novos nomes ao DataFrame
df_coef.columns = new_columns

In [18]:
output_path = '../excel/out/df_coef_exported.xlsx'
df_coef.to_excel(output_path, index=False)